source "http://rubygems.org"

gem "sinatra"

gem "sequel"

gem "sqlite3-ruby", :platforms => :ruby
gem "jdbc-sqlite3", :platforms => :jruby

gem "rereplay", :git => "git@github.com:nanodeath/ReReplay.git"
